apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservices
spec:
  ingressClassName: nginx
  rules:
  - host: myserver.org
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: 80
