# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: nginx-deployment
  replica: 3
  labels:
    app: nginx   
  containers: 
     name: nginx-container
     port: 80
     image: nginx

service:
  name: nginx-service
  Selector:      
    app: nginx
  protocol: TCP
  port: 80
  targetPort: 30578  
