# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: application_name
  replica: 3
  labels:
    app: nginx   
  containers: 
     name: container_name
     port: 80
     image: nginx

service:
  name: temo_service
  Selector:      
    app: nginx
  protocol: TCP
  port: 80
  targetPort: 9736  
