# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: application-name
  replica: 3
  labels:
    app: nginx   
  containers: 
     name: container-name
     port: 80
     image: nginx

service:
  name: temo-service
  Selector:      
    app: nginx
  protocol: TCP
  port: 80
  targetPort: 9736  
